# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "win81x64"

  config.vm.guest = :windows

  config.vm.network :forwarded_port, guest: 3389, host: 13390
  config.vm.communicator = "winrm"
  config.vm.network :forwarded_port, guest: 5985, host: 15985, id: "winrm", auto_correct:true

  config.winrm.port = 15985
  config.winrm.guest_port = 5985

  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.cpus = 2
    v.memory = 2048
  end
end
