source 'https://rubygems.org'

gem 'watir-webdriver'
gem 'headless'
gem 'page-object'
#gem 'google_drive'
#gem 'google-api-client'
gem 'table_print'

gem 'google-api-client', '~> 0.9'
gem 'thor', '~> 0.19'
gem 'os', '~> 0.9'
gem 'rmail', '~> 1.1'
gem 'dotenv'
